require('cfg.impatient')
require('cfg.options')
require('cfg.keymaps')
require('cfg.plugins')
require('cfg.colorscheme')
require('cfg.completions')
require('cfg.lsp')
require('cfg.telescope')
require('cfg.treesitter')
require('cfg.autopairs')
require('cfg.comment')
require('cfg.gitsigns')
-- require('cfg.nvim-tree')
require('cfg.bufferline')
-- require "cfg.lualine"
require('cfg.lualine-simple')
require('cfg.toggleterm')
require('cfg.project')
require('cfg.indentline')
require('cfg.alpha')
require('cfg.whichkey')
require('cfg.autocommands')
